export enum NotesCategories{
    'ALERGIE' = 0,
    'PRZEBYTE CHOROBY' = 1,
    'WAŻNE WYDARZENIA' = 2,
    'NIEPOKOJĄCE ZDARZENIA/OBJAWY' = 3,
    'ULUBIONE ZABAWY/PRZEDMIOTY' = 4,
    'ULUBIONE DANIA' = 5
}